/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.RtaCliente;
import dao.RtaClientes_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author 
 */
public class JDlgRtaClientes extends javax.swing.JDialog {

    
     private boolean incluindo;
     RtaCliente rtaCliente;
     RtaClientes_DAO rtaClientes_DAO;
     MaskFormatter mascaraCPF, mascaraTelefone, mascaraCelular, mascaraRg;
    
    /**
     * Creates new form JDglRtaClientes
     */
    public JDlgRtaClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Util.habilitar(false,jBtnCancelar,jBtnConfirmar,jTxtNome,jFmtCep,jFmtCpf,jFmtRg,jTxtBairro,jTxtEndereco,jTxtRua,jTxtNumRua,jTxtComple,jCboPais,jFmtTel,jFmtCelular,jCboEstadoC,jtxtGenero,jTxtCodigo );
        Util.habilitar(true, jBtnIncluir,jBtnAlterar,jBtnPesq);      
        setTitle("Cliente");
        setLocationRelativeTo(null);
        rtaClientes_DAO = new RtaClientes_DAO();
        rtaCliente = new RtaCliente();
          try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraTelefone = new MaskFormatter("(##)# ####-####");
            mascaraCelular = new MaskFormatter("(##)#####-####");
            mascaraRg = new MaskFormatter("##.###.###-#");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgRtaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
        jFmtTel.setFormatterFactory(new DefaultFormatterFactory(mascaraTelefone));
        jFmtCelular.setFormatterFactory(new DefaultFormatterFactory(mascaraCelular));
        jFmtRg.setFormatterFactory(new DefaultFormatterFactory(mascaraRg));
     
    }
    
    public RtaCliente viewBean(){
        rtaCliente = new RtaCliente();
        
        rtaCliente.setIdrtaCliente(Util.strInt(jTxtCodigo.getText()));
        rtaCliente.setRtaNome(jTxtNome.getText());
        rtaCliente.setRtaCpf(jFmtCpf.getText());
        rtaCliente.setRtaCep(jFmtCep.getText());
        rtaCliente.setRtaRg(jFmtRg.getText());
        rtaCliente.setRtaPais(jCboPais.getSelectedIndex());
        rtaCliente.setRtaRua(jTxtRua.getText());
        rtaCliente.setRtaNumeroRua(jTxtNumRua.getText());
        rtaCliente.setRtaBairro(jTxtBairro.getText());
        rtaCliente.setRtaComplemento(jTxtComple.getText());
        rtaCliente.setRtaGenero(jtxtGenero.getText());
        rtaCliente.setRtaCelular(jFmtCelular.getText());
        rtaCliente.setRtaTelefone(jFmtTel.getText());
        rtaCliente.setRtaEstadoCivil(jCboEstadoC.getSelectedIndex());
        rtaCliente.setRtaEndereco(jTxtEndereco.getText());

         return this.rtaCliente;
    }
    
    public void beanView(RtaCliente rtaCliente){
        
        jTxtCodigo.setText(Util.intStr(rtaCliente.getIdrtaCliente()));
        jTxtNome.setText(rtaCliente.getRtaNome());
        jFmtCpf.setText(rtaCliente.getRtaCpf());
        jFmtRg.setText(rtaCliente.getRtaRg());
        jCboPais.setSelectedIndex(rtaCliente.getRtaPais());
        jFmtCep.setText(rtaCliente.getRtaCep());
        jTxtRua.setText(rtaCliente.getRtaRua());
        jTxtNumRua.setText(rtaCliente.getRtaNumeroRua());
        jTxtBairro.setText(rtaCliente.getRtaBairro());
        jTxtComple.setText(rtaCliente.getRtaComplemento());
        jtxtGenero.setText(rtaCliente.getRtaGenero());
        jFmtCelular.setText(rtaCliente.getRtaCelular());
        jFmtTel.setText(rtaCliente.getRtaTelefone());
        jCboEstadoC.setSelectedIndex(rtaCliente.getRtaEstadoCivil());
        jTxtEndereco.setText(rtaCliente.getRtaEndereco());

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        pais = new javax.swing.JLabel();
        jFmtCep = new javax.swing.JTextField();
        Cep = new javax.swing.JLabel();
        RG = new javax.swing.JLabel();
        rua = new javax.swing.JLabel();
        jTxtRua = new javax.swing.JTextField();
        bairro = new javax.swing.JLabel();
        jTxtBairro = new javax.swing.JTextField();
        endere = new javax.swing.JLabel();
        jTxtEndereco = new javax.swing.JTextField();
        cell = new javax.swing.JLabel();
        comple = new javax.swing.JLabel();
        jTxtComple = new javax.swing.JTextField();
        genero = new javax.swing.JLabel();
        jtxtGenero = new javax.swing.JTextField();
        tell = new javax.swing.JLabel();
        jTxtEstadoC = new javax.swing.JLabel();
        jCboEstadoC = new javax.swing.JComboBox<>();
        jCboPais = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jBtnPesq = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        endere1 = new javax.swing.JLabel();
        jTxtNumRua = new javax.swing.JTextField();
        jFmtCpf = new javax.swing.JFormattedTextField();
        jFmtTel = new javax.swing.JFormattedTextField();
        jFmtCelular = new javax.swing.JFormattedTextField();
        jFmtRg = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nome.setText("nome");

        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        cpf.setText("cpf");

        pais.setText("Pais");

        jFmtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCepActionPerformed(evt);
            }
        });

        Cep.setText("CEP");

        RG.setText("RG");

        rua.setText("Rua");

        jTxtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRuaActionPerformed(evt);
            }
        });

        bairro.setText("Bairro");

        jTxtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairroActionPerformed(evt);
            }
        });

        endere.setText("Endereço");

        jTxtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEnderecoActionPerformed(evt);
            }
        });

        cell.setText("Celular");

        comple.setText("Complemento (Opcional)");

        jTxtComple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCompleActionPerformed(evt);
            }
        });

        genero.setText("Genero");

        jtxtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGeneroActionPerformed(evt);
            }
        });

        tell.setText("Telefone fixo (Opcional)");

        jTxtEstadoC.setText("Estado Civil");

        jCboEstadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Divorciado(a)", "Viuvo(a)", "Namorando" }));
        jCboEstadoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboEstadoCActionPerformed(evt);
            }
        });

        jCboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brasil", "Paraguai", " " }));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SearchIcon.png"))); // NOI18N
        jBtnPesq.setText("Perquisar");
        jBtnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CancelIcon.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ConfirmIcon.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteIcon.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditIcon.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ConfirmIcon.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jBtnCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnPesq)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPesq)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnIncluir)))
        );

        jLabel1.setText("codigo");

        endere1.setText("numero Rua");

        jTxtNumRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumRuaActionPerformed(evt);
            }
        });

        jFmtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RG)
                                    .addComponent(pais)
                                    .addComponent(jFmtCep, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Cep)
                                    .addComponent(rua)
                                    .addComponent(jTxtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(nome)
                                    .addComponent(jTxtNome)
                                    .addComponent(cpf)
                                    .addComponent(jCboPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtCodigo)
                                    .addComponent(jFmtCpf)
                                    .addComponent(jFmtRg))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endere)
                                    .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bairro)
                                    .addComponent(comple)
                                    .addComponent(jTxtComple, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genero)
                                    .addComponent(cell)
                                    .addComponent(tell)
                                    .addComponent(jtxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtEstadoC)
                                    .addComponent(jCboEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFmtCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(jFmtTel, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jTxtNumRua, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endere1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtComple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTxtEstadoC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCboEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RG)
                        .addGap(1, 1, 1)
                        .addComponent(jFmtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Cep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFmtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endere1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNumRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jFmtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCepActionPerformed

    private void jTxtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRuaActionPerformed

    private void jTxtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairroActionPerformed

    private void jTxtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEnderecoActionPerformed

    private void jTxtCompleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCompleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCompleActionPerformed

    private void jtxtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGeneroActionPerformed

    private void jCboEstadoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboEstadoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboEstadoCActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesq);
        incluindo = true;

        Util.limparCampos(jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco);
                
                 
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        Util.habilitar(true, jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco, jBtnConfirmar, jBtnCancelar);
        incluindo = false;
        
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
 if (Util.perguntar("Deseja excluir o registro?") == true){
           rtaCliente = viewBean();
           rtaClientes_DAO.delete(rtaCliente);
       }
       else {
        
            Util.mensagem("Exclusão cancelada");
       
 }
        Util.limparCampos(jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesq);
        Util.habilitar(false, jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco, jBtnConfirmar, jBtnCancelar);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
            rtaCliente = viewBean();
            rtaClientes_DAO = new RtaClientes_DAO();
        if (incluindo ==true ){
            rtaClientes_DAO.insert(rtaCliente);}
        else{
            rtaClientes_DAO.update(rtaCliente);               
            }
        Util.limparCampos(jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesq);
        Util.habilitar(false, jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco, jBtnConfirmar, jBtnCancelar);
   
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.mensagem("Operação cancelada");
        Util.limparCampos(jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco);
        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesq);
        Util.habilitar(false, jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco, jBtnConfirmar, jBtnCancelar);
   
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqActionPerformed
        
        JDlgClientesPesquisa jDlgClientesPesquisa = new JDlgClientesPesquisa(null, true);
        jDlgClientesPesquisa.setTelaAnterior(this);
        jDlgClientesPesquisa.setVisible(true);
        Util.habilitar(true, jBtnConfirmar, jBtnAlterar, jBtnExcluir, jBtnCancelar);
        Util.habilitar(false, jTxtBairro,jTxtCodigo, jTxtNome, jFmtCelular, jFmtCpf, jFmtCep,jFmtRg, jCboPais,jCboEstadoC,jFmtTel,jTxtRua,jTxtNumRua,jTxtComple,jtxtGenero,jTxtEndereco, jBtnIncluir, jBtnPesq);
   

    }//GEN-LAST:event_jBtnPesqActionPerformed

    private void jTxtNumRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumRuaActionPerformed

    private void jFmtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtaClientes dialog = new JDlgRtaClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cep;
    private javax.swing.JLabel RG;
    private javax.swing.JLabel bairro;
    private javax.swing.JLabel cell;
    private javax.swing.JLabel comple;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel endere;
    private javax.swing.JLabel endere1;
    private javax.swing.JLabel genero;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesq;
    private javax.swing.JComboBox<String> jCboEstadoC;
    private javax.swing.JComboBox<String> jCboPais;
    private javax.swing.JFormattedTextField jFmtCelular;
    private javax.swing.JTextField jFmtCep;
    private javax.swing.JFormattedTextField jFmtCpf;
    private javax.swing.JFormattedTextField jFmtRg;
    private javax.swing.JFormattedTextField jFmtTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtComple;
    private javax.swing.JTextField jTxtEndereco;
    private javax.swing.JLabel jTxtEstadoC;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNumRua;
    private javax.swing.JTextField jTxtRua;
    private javax.swing.JTextField jtxtGenero;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel pais;
    private javax.swing.JLabel rua;
    private javax.swing.JLabel tell;
    // End of variables declaration//GEN-END:variables
}
