/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import bean.RtaProdutos;
import bean.RtaVendas;
import bean.RtaVendasproduto;
import dao.RtaProduto_DAO;
import dao.RtaVendasProduto_DAO;
import dao.RtaVendas_DAO;
import java.util.List;
import tools.Util;

/**
 *
 * @author rafae
 */
public class JDlgRtaVendasProduto extends javax.swing.JDialog {
public RtaVendas rtaVendas;
public JDlgRtaVendas jDlgRtaVendas;
public RtaProdutos rtaProdutos;
public RtaProduto_DAO rtaProduto_DAO;
 public RtaVendas_DAO rtaVendas_DAO;
 public RtaVendasProduto_DAO rtaVendasProduto_DAO;
 public RtaVendasproduto rtaVendasproduto;
 public VendasProdutoController vendasProdutoController;
    /**
     * Creates new form JDlgRtaVendasproduto
     */
    public JDlgRtaVendasProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
        setLocationRelativeTo(null);
        setTitle("Produtos do pedido");
         Util.habilitar(false,  jTxtTotal);
         
        
          rtaProduto_DAO = new RtaProduto_DAO();
        List lista = rtaProduto_DAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
             rtaProdutos= (RtaProdutos) lista.get(i);
            jCboProdutos.addItem(rtaProdutos);
        }
        
//        fornecedor_DAO = new DrfFornecedor_DAO();
//        List listaFornecedor = fornecedor_DAO.listAll();
//        for (int i = 0; i < listaFornecedor.size(); i++) {
//            fornecedor = (DrfFornecedor) listaFornecedor.get(i);
//            jCboFornecedor.addItem(fornecedor);
        
    }
         public void setTelaAnterior(JDlgRtaVendas jDlgRtaVendas) {
        this.jDlgRtaVendas = jDlgRtaVendas;
        

    }

   
    

    public void beanView(RtaVendasproduto rtaVendasproduto) {
        jTxtQuantidade.setText((rtaVendasproduto.getRtaQuantidadel()));
        jCboProdutos.setSelectedItem(rtaVendasproduto.getRtaProdutos());
       jTxtUnitario.setText(Util.doubleStr(rtaVendasproduto.getRtaPreco()));
       //jTxtTotal.setText(Util.doubleStr(compra.getDrfValorTotalCompra()));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JTextField();
        jBtnCancelar = new javax.swing.JButton();
        jBtnOk = new javax.swing.JButton();
        jCboProdutos = new javax.swing.JComboBox<RtaProdutos>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtUnitario = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Total");

        jTxtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtQuantidadeActionPerformed(evt);
            }
        });
        jTxtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeKeyReleased(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnOk.setText("OK");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });

        jCboProdutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutosItemStateChanged(evt);
            }
        });
        jCboProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboProdutosActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Valor Unitario");

        jTxtUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUnitarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 103, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOk)
                    .addComponent(jBtnCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:

        Util.mensagem("Cancelamento concluido");
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
         rtaVendasproduto = new RtaVendasproduto();
        rtaVendasproduto.setRtaProdutos((RtaProdutos) jCboProdutos.getSelectedItem() );
        rtaVendasproduto.setRtaQuantidadel((jTxtQuantidade.getText() ));
        rtaVendasproduto.setRtaPreco(Util.strDouble(jTxtUnitario.getText()));
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
           jDlgRtaVendas.vendasProdutoController.addBean(rtaVendasproduto);
        } else {            
            jDlgRtaVendas.vendasProdutoController.updateBean(jDlgRtaVendas.getSelectedRowProd(), rtaVendasproduto);
        }
        setVisible(false);
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jCboProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboProdutosActionPerformed

    private void jCboProdutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutosItemStateChanged
jTxtQuantidade.setText("1");
 rtaProdutos = (RtaProdutos) jCboProdutos.getSelectedItem();
jTxtUnitario.setText(Util.doubleStr(rtaProdutos.getRtaValor()));
        jTxtTotal.setText(jTxtUnitario.getText());
    }//GEN-LAST:event_jCboProdutosItemStateChanged

    private void jTxtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeKeyPressed

    private void jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKeyReleased
     if(jTxtQuantidade.getText().isEmpty() == false){
     double unitario = Util.strDouble(jTxtUnitario.getText());
     double quantidade = Util.strDouble(jTxtQuantidade.getText());
     jTxtTotal.setText(Util.doubleStr(quantidade*unitario));
     }
     else{
     jTxtTotal.setText("0");
     
     
     }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeKeyReleased

    private void jTxtUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUnitarioKeyReleased
 if(jTxtUnitario.getText().isEmpty() == false){
     double unitario = Util.strDouble(jTxtQuantidade.getText());
     double quantidade = Util.strDouble(jTxtUnitario.getText());
     jTxtTotal.setText(Util.doubleStr(quantidade*unitario));
     }
     else{
     jTxtTotal.setText("0");
     
     
     }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUnitarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtaVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtaVendasProduto dialog = new JDlgRtaVendasProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox<RtaProdutos> jCboProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtUnitario;
    // End of variables declaration//GEN-END:variables
}
