package bean;
// Generated 16/09/2023 19:54:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RtaCliente generated by hbm2java
 */
@Entity
@Table(name="rta_cliente"
    ,catalog="db_raul_torres"
)
public class RtaCliente  implements java.io.Serializable {


     private int idrtaCliente;
     private String rtaNome;
     private String rtaCpf;
     private String rtaRg;
     private String rtaPais;
     private String rtaCep;
     private String rtaRua;
     private String rtaEndereco;
     private String rtaBairro;
     private String rtaNumeroRua;
     private String rtaComplemento;
     private String rtaGenero;
     private String rtaCelular;
     private String rtaTelefone;
     private String rtaEstadoCivil;
     private Set rtaVendases = new HashSet(0);

    public RtaCliente() {
    }

	
    public RtaCliente(int idrtaCliente, String rtaNome, String rtaCpf, String rtaRg, String rtaPais, String rtaCep, String rtaRua, String rtaEndereco, String rtaBairro, String rtaNumeroRua, String rtaGenero, String rtaCelular) {
        this.idrtaCliente = idrtaCliente;
        this.rtaNome = rtaNome;
        this.rtaCpf = rtaCpf;
        this.rtaRg = rtaRg;
        this.rtaPais = rtaPais;
        this.rtaCep = rtaCep;
        this.rtaRua = rtaRua;
        this.rtaEndereco = rtaEndereco;
        this.rtaBairro = rtaBairro;
        this.rtaNumeroRua = rtaNumeroRua;
        this.rtaGenero = rtaGenero;
        this.rtaCelular = rtaCelular;
    }
    public RtaCliente(int idrtaCliente, String rtaNome, String rtaCpf, String rtaRg, String rtaPais, String rtaCep, String rtaRua, String rtaEndereco, String rtaBairro, String rtaNumeroRua, String rtaComplemento, String rtaGenero, String rtaCelular, String rtaTelefone, String rtaEstadoCivil, Set rtaVendases) {
       this.idrtaCliente = idrtaCliente;
       this.rtaNome = rtaNome;
       this.rtaCpf = rtaCpf;
       this.rtaRg = rtaRg;
       this.rtaPais = rtaPais;
       this.rtaCep = rtaCep;
       this.rtaRua = rtaRua;
       this.rtaEndereco = rtaEndereco;
       this.rtaBairro = rtaBairro;
       this.rtaNumeroRua = rtaNumeroRua;
       this.rtaComplemento = rtaComplemento;
       this.rtaGenero = rtaGenero;
       this.rtaCelular = rtaCelular;
       this.rtaTelefone = rtaTelefone;
       this.rtaEstadoCivil = rtaEstadoCivil;
       this.rtaVendases = rtaVendases;
    }
   
     @Id 

    
    @Column(name="idrta_cliente", unique=true, nullable=false)
    public int getIdrtaCliente() {
        return this.idrtaCliente;
    }
    
    public void setIdrtaCliente(int idrtaCliente) {
        this.idrtaCliente = idrtaCliente;
    }

    
    @Column(name="rta_nome", nullable=false, length=45)
    public String getRtaNome() {
        return this.rtaNome;
    }
    
    public void setRtaNome(String rtaNome) {
        this.rtaNome = rtaNome;
    }

    
    @Column(name="rta_cpf", nullable=false, length=25)
    public String getRtaCpf() {
        return this.rtaCpf;
    }
    
    public void setRtaCpf(String rtaCpf) {
        this.rtaCpf = rtaCpf;
    }

    
    @Column(name="rta_rg", nullable=false, length=25)
    public String getRtaRg() {
        return this.rtaRg;
    }
    
    public void setRtaRg(String rtaRg) {
        this.rtaRg = rtaRg;
    }

    
    @Column(name="rta_pais", nullable=false, length=50)
    public String getRtaPais() {
        return this.rtaPais;
    }
    
    public void setRtaPais(String rtaPais) {
        this.rtaPais = rtaPais;
    }

    
    @Column(name="rta_cep", nullable=false, length=20)
    public String getRtaCep() {
        return this.rtaCep;
    }
    
    public void setRtaCep(String rtaCep) {
        this.rtaCep = rtaCep;
    }

    
    @Column(name="rta_rua", nullable=false, length=50)
    public String getRtaRua() {
        return this.rtaRua;
    }
    
    public void setRtaRua(String rtaRua) {
        this.rtaRua = rtaRua;
    }

    
    @Column(name="rta_endereco", nullable=false, length=50)
    public String getRtaEndereco() {
        return this.rtaEndereco;
    }
    
    public void setRtaEndereco(String rtaEndereco) {
        this.rtaEndereco = rtaEndereco;
    }

    
    @Column(name="rta_bairro", nullable=false, length=50)
    public String getRtaBairro() {
        return this.rtaBairro;
    }
    
    public void setRtaBairro(String rtaBairro) {
        this.rtaBairro = rtaBairro;
    }

    
    @Column(name="rta_numeroRua", nullable=false, length=50)
    public String getRtaNumeroRua() {
        return this.rtaNumeroRua;
    }
    
    public void setRtaNumeroRua(String rtaNumeroRua) {
        this.rtaNumeroRua = rtaNumeroRua;
    }

    
    @Column(name="rta_complemento", length=50)
    public String getRtaComplemento() {
        return this.rtaComplemento;
    }
    
    public void setRtaComplemento(String rtaComplemento) {
        this.rtaComplemento = rtaComplemento;
    }

    
    @Column(name="rta_genero", nullable=false, length=30)
    public String getRtaGenero() {
        return this.rtaGenero;
    }
    
    public void setRtaGenero(String rtaGenero) {
        this.rtaGenero = rtaGenero;
    }

    
    @Column(name="rta_celular", nullable=false, length=15)
    public String getRtaCelular() {
        return this.rtaCelular;
    }
    
    public void setRtaCelular(String rtaCelular) {
        this.rtaCelular = rtaCelular;
    }

    
    @Column(name="rta_telefone", length=15)
    public String getRtaTelefone() {
        return this.rtaTelefone;
    }
    
    public void setRtaTelefone(String rtaTelefone) {
        this.rtaTelefone = rtaTelefone;
    }

    
    @Column(name="rta_estadoCivil", length=25)
    public String getRtaEstadoCivil() {
        return this.rtaEstadoCivil;
    }
    
    public void setRtaEstadoCivil(String rtaEstadoCivil) {
        this.rtaEstadoCivil = rtaEstadoCivil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rtaCliente")
    public Set getRtaVendases() {
        return this.rtaVendases;
    }
    
    public void setRtaVendases(Set rtaVendases) {
        this.rtaVendases = rtaVendases;
    }




}


