package bean;
// Generated 16/09/2023 19:54:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RtaGrupo generated by hbm2java
 */
@Entity
@Table(name="rta_grupo"
    ,catalog="db_raul_torres"
)
public class RtaGrupo  implements java.io.Serializable {


     private int idrtaGrupo;
     private String rtaDescricao;
     private String rtaMassa;
     private String rtaRecheio;
     private String rtaDecoracao;

    public RtaGrupo() {
    }

	
    public RtaGrupo(int idrtaGrupo, String rtaDescricao, String rtaMassa, String rtaRecheio) {
        this.idrtaGrupo = idrtaGrupo;
        this.rtaDescricao = rtaDescricao;
        this.rtaMassa = rtaMassa;
        this.rtaRecheio = rtaRecheio;
    }
    public RtaGrupo(int idrtaGrupo, String rtaDescricao, String rtaMassa, String rtaRecheio, String rtaDecoracao) {
       this.idrtaGrupo = idrtaGrupo;
       this.rtaDescricao = rtaDescricao;
       this.rtaMassa = rtaMassa;
       this.rtaRecheio = rtaRecheio;
       this.rtaDecoracao = rtaDecoracao;
    }
   
     @Id 

    
    @Column(name="idrta_grupo", unique=true, nullable=false)
    public int getIdrtaGrupo() {
        return this.idrtaGrupo;
    }
    
    public void setIdrtaGrupo(int idrtaGrupo) {
        this.idrtaGrupo = idrtaGrupo;
    }

    
    @Column(name="rta_descricao", nullable=false, length=45)
    public String getRtaDescricao() {
        return this.rtaDescricao;
    }
    
    public void setRtaDescricao(String rtaDescricao) {
        this.rtaDescricao = rtaDescricao;
    }

    
    @Column(name="rta_massa", nullable=false, length=50)
    public String getRtaMassa() {
        return this.rtaMassa;
    }
    
    public void setRtaMassa(String rtaMassa) {
        this.rtaMassa = rtaMassa;
    }

    
    @Column(name="rta_recheio", nullable=false, length=50)
    public String getRtaRecheio() {
        return this.rtaRecheio;
    }
    
    public void setRtaRecheio(String rtaRecheio) {
        this.rtaRecheio = rtaRecheio;
    }

    
    @Column(name="rta_decoracao", length=50)
    public String getRtaDecoracao() {
        return this.rtaDecoracao;
    }
    
    public void setRtaDecoracao(String rtaDecoracao) {
        this.rtaDecoracao = rtaDecoracao;
    }




}


