package bean;
// Generated 19/10/2023 21:48:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RtaProdutos generated by hbm2java
 */
@Entity
@Table(name="rta_produtos"
    ,catalog="db_raul_torres"
)
public class RtaProdutos  implements java.io.Serializable {


     private int idrtaProdutos;
     private int rtaGrupo;
     private String rtaNome;
     private double rtaValor;
     private String rtaDescricao;
    

    public RtaProdutos() {
    }

	
    public RtaProdutos(int idrtaProdutos, int rtaGrupo, String rtaNome, double rtaValor, String rtaDescricao) {
        this.idrtaProdutos = idrtaProdutos;
        this.rtaGrupo = rtaGrupo;
        this.rtaNome = rtaNome;
        this.rtaValor = rtaValor;
        this.rtaDescricao = rtaDescricao;
    }
   
   
     @Id 

    
    @Column(name="idrta_produtos", unique=true, nullable=false)
    public int getIdrtaProdutos() {
        return this.idrtaProdutos;
    }
    
    public void setIdrtaProdutos(int idrtaProdutos) {
        this.idrtaProdutos = idrtaProdutos;
    }

    
    @Column(name="rta_grupo", nullable=false)
    public int getRtaGrupo() {
        return this.rtaGrupo;
    }
    
    public void setRtaGrupo(int rtaGrupo) {
        this.rtaGrupo = rtaGrupo;
    }

    
    @Column(name="rta_nome", nullable=false, length=45)
    public String getRtaNome() {
        return this.rtaNome;
    }
    
    public void setRtaNome(String rtaNome) {
        this.rtaNome = rtaNome;
    }

    
    @Column(name="rta_valor", nullable=false, precision=10)
    public double getRtaValor() {
        return this.rtaValor;
    }
    
    public void setRtaValor(double rtaValor) {
        this.rtaValor = rtaValor;
    }

    
    @Column(name="rta_descricao", nullable=false, length=45)
    public String getRtaDescricao() {
        return this.rtaDescricao;
    }
    
    public void setRtaDescricao(String rtaDescricao) {
        this.rtaDescricao = rtaDescricao;
    }
@Override
    public String toString(){
    return this.getRtaNome();
    }
    @Override
    public boolean equals (Object object){
    if(object instanceof RtaProdutos){
      RtaProdutos produtos = (RtaProdutos) object;
    if(this.getIdrtaProdutos()==produtos.getIdrtaProdutos()){
    return true;
    } }
    return false;
}





}


