package bean;
// Generated 22/09/2023 23:51:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RtaProdutos generated by hbm2java
 */
@Entity
@Table(name="rta_produtos"
    ,catalog="db_raul_torres"
)
public class RtaProdutos  implements java.io.Serializable {


     private int idrtaProdutos;
     private int rtaGrupo;
     private String rtaNome;
     private BigDecimal rtaValor;
    

    public RtaProdutos() {
    }

	
    public RtaProdutos(int idrtaProdutos, int rtaGrupo, String rtaNome, BigDecimal rtaValor) {
        this.idrtaProdutos = idrtaProdutos;
        this.rtaGrupo = rtaGrupo;
        this.rtaNome = rtaNome;
        this.rtaValor = rtaValor;
    }
  
   
     @Id 

    
    @Column(name="idrta_produtos", unique=true, nullable=false)
    public int getIdrtaProdutos() {
        return this.idrtaProdutos;
    }
    
    public void setIdrtaProdutos(int idrtaProdutos) {
        this.idrtaProdutos = idrtaProdutos;
    }

    
    @Column(name="rta_grupo", nullable=false)
    public int getRtaGrupo() {
        return this.rtaGrupo;
    }
    
    public void setRtaGrupo(int rtaGrupo) {
        this.rtaGrupo = rtaGrupo;
    }

    
    @Column(name="rta_nome", nullable=false, length=45)
    public String getRtaNome() {
        return this.rtaNome;
    }
    
    public void setRtaNome(String rtaNome) {
        this.rtaNome = rtaNome;
    }

    
    @Column(name="rta_valor", nullable=false, precision=10)
    public BigDecimal getRtaValor() {
        return this.rtaValor;
    }
    
    public void setRtaValor(BigDecimal rtaValor) {
        this.rtaValor = rtaValor;
    }






}


