package bean;
// Generated 19/10/2023 21:48:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RtaVendasproduto generated by hbm2java
 */
@Entity
@Table(name="rta_vendasProduto"
    ,catalog="db_raul_torres"
)
public class RtaVendasproduto  implements java.io.Serializable {


     private int idrtaVendasProduto;
     private RtaProdutos rtaProdutos;
     private RtaVendas rtaVendas;
     private String rtaQuantidadel;
     private double rtaPreco;

    public RtaVendasproduto() {
    }

    public RtaVendasproduto(int idrtaVendasProduto, RtaProdutos rtaProdutos, RtaVendas rtaVendas, String rtaQuantidadel, double rtaPreco) {
       this.idrtaVendasProduto = idrtaVendasProduto;
       this.rtaProdutos = rtaProdutos;
       this.rtaVendas = rtaVendas;
       this.rtaQuantidadel = rtaQuantidadel;
       this.rtaPreco = rtaPreco;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY) 

    
    @Column(name="idrta_vendasProduto", unique=true, nullable=false)
    public int getIdrtaVendasProduto() {
        return this.idrtaVendasProduto;
    }
    
    public void setIdrtaVendasProduto(int idrtaVendasProduto) {
        this.idrtaVendasProduto = idrtaVendasProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rta_FKProdutos", nullable=false)
    public RtaProdutos getRtaProdutos() {
        return this.rtaProdutos;
    }
    
    public void setRtaProdutos(RtaProdutos rtaProdutos) {
        this.rtaProdutos = rtaProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rta_FKVendas", nullable=false)
    public RtaVendas getRtaVendas() {
        return this.rtaVendas;
    }
    
    public void setRtaVendas(RtaVendas rtaVendas) {
        this.rtaVendas = rtaVendas;
    }

    
    @Column(name="rta_quantidadel", nullable=false, length=50)
    public String getRtaQuantidadel() {
        return this.rtaQuantidadel;
    }
    
    public void setRtaQuantidadel(String rtaQuantidadel) {
        this.rtaQuantidadel = rtaQuantidadel;
    }

    
    @Column(name="rta_preco", nullable=false, precision=10)
    public double getRtaPreco() {
        return this.rtaPreco;
    }
    
    public void setRtaPreco(double rtaPreco) {
        this.rtaPreco = rtaPreco;
    }




}


